apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-kubernetes
    spec:     # pod spec                  
      containers: 
      - name: hello-kubernetes
        image: stefanreichert/hello-kubernetes:latest # image we pushed
        ports:
        - containerPort: 3000